# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Berk/Desktop/FPGA/UMRAM/BramWithIP/BramWithIP.srcs/sources_1/bd/dizaynnn/ip/dizaynnn_clk_wiz_0_0/dizaynnn_clk_wiz_0_0.xci
# IP: The module: 'dizaynnn_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Berk/Desktop/FPGA/UMRAM/BramWithIP/BramWithIP.srcs/sources_1/bd/dizaynnn/ip/dizaynnn_clk_wiz_0_0/dizaynnn_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dizaynnn_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Berk/Desktop/FPGA/UMRAM/BramWithIP/BramWithIP.srcs/sources_1/bd/dizaynnn/ip/dizaynnn_clk_wiz_0_0/dizaynnn_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'dizaynnn_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Berk/Desktop/FPGA/UMRAM/BramWithIP/BramWithIP.srcs/sources_1/bd/dizaynnn/ip/dizaynnn_clk_wiz_0_0/dizaynnn_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dizaynnn_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: c:/Users/Berk/Desktop/FPGA/UMRAM/BramWithIP/BramWithIP.srcs/sources_1/bd/dizaynnn/ip/dizaynnn_clk_wiz_0_0/dizaynnn_clk_wiz_0_0.xci
# IP: The module: 'dizaynnn_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Berk/Desktop/FPGA/UMRAM/BramWithIP/BramWithIP.srcs/sources_1/bd/dizaynnn/ip/dizaynnn_clk_wiz_0_0/dizaynnn_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dizaynnn_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Berk/Desktop/FPGA/UMRAM/BramWithIP/BramWithIP.srcs/sources_1/bd/dizaynnn/ip/dizaynnn_clk_wiz_0_0/dizaynnn_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'dizaynnn_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/Berk/Desktop/FPGA/UMRAM/BramWithIP/BramWithIP.srcs/sources_1/bd/dizaynnn/ip/dizaynnn_clk_wiz_0_0/dizaynnn_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dizaynnn_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
