# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1761-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Berk/Desktop/FPGA/UMRAM/BramWithIP/BramWithIP.cache/wt [current_project]
set_property parent.project_path C:/Users/Berk/Desktop/FPGA/UMRAM/BramWithIP/BramWithIP.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:vc707:part0:1.3 [current_project]
set_property ip_repo_paths c:/Users/Berk/Desktop/FPGA/UMRAM/Bram_Deneme/Bram_Deneme.srcs/sources_1 [current_project]
set_property ip_output_repo c:/Users/Berk/Desktop/FPGA/UMRAM/BramWithIP/BramWithIP.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/Users/Berk/Desktop/FPGA/UMRAM/BramWithIP/BramWithIP.srcs/sources_1/bd/dizaynnn/hdl/dizaynnn_wrapper.vhd
add_files C:/Users/Berk/Desktop/FPGA/UMRAM/BramWithIP/BramWithIP.srcs/sources_1/bd/dizaynnn/dizaynnn.bd
set_property used_in_implementation false [get_files -all c:/Users/Berk/Desktop/FPGA/UMRAM/BramWithIP/BramWithIP.srcs/sources_1/bd/dizaynnn/ip/dizaynnn_clk_wiz_0_0/dizaynnn_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Berk/Desktop/FPGA/UMRAM/BramWithIP/BramWithIP.srcs/sources_1/bd/dizaynnn/ip/dizaynnn_clk_wiz_0_0/dizaynnn_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Berk/Desktop/FPGA/UMRAM/BramWithIP/BramWithIP.srcs/sources_1/bd/dizaynnn/ip/dizaynnn_clk_wiz_0_0/dizaynnn_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Berk/Desktop/FPGA/UMRAM/BramWithIP/BramWithIP.srcs/sources_1/bd/dizaynnn/ip/dizaynnn_blk_mem_gen_0_0/dizaynnn_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/Berk/Desktop/FPGA/UMRAM/BramWithIP/BramWithIP.srcs/sources_1/bd/dizaynnn/dizaynnn_ooc.xdc]
set_property is_locked true [get_files C:/Users/Berk/Desktop/FPGA/UMRAM/BramWithIP/BramWithIP.srcs/sources_1/bd/dizaynnn/dizaynnn.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top dizaynnn_wrapper -part xc7vx485tffg1761-2


write_checkpoint -force -noxdef dizaynnn_wrapper.dcp

catch { report_utilization -file dizaynnn_wrapper_utilization_synth.rpt -pb dizaynnn_wrapper_utilization_synth.pb }
