# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Berk/Desktop/FPGA/UMRAM/Ethernet/Ethernet.srcs/sources_1/bd/design_1/ip/design_1_axi_ethernet_0_1/design_1_axi_ethernet_0_1.xci
# IP: The module: 'design_1_axi_ethernet_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/Berk/Desktop/FPGA/UMRAM/Ethernet/Ethernet.srcs/sources_1/bd/design_1/ip/design_1_axi_ethernet_0_1/bd_0/bd_525a.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_525a || ORIG_REF_NAME==bd_525a}]

# IP: c:/Users/Berk/Desktop/FPGA/UMRAM/Ethernet/Ethernet.srcs/sources_1/bd/design_1/ip/design_1_axi_ethernet_0_1/bd_0/ip/ip_0/bd_525a_eth_buf_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_525a_eth_buf_0 || ORIG_REF_NAME==bd_525a_eth_buf_0}]

# IP: c:/Users/Berk/Desktop/FPGA/UMRAM/Ethernet/Ethernet.srcs/sources_1/bd/design_1/ip/design_1_axi_ethernet_0_1/bd_0/ip/ip_1/bd_525a_eth_mac_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_525a_eth_mac_0 || ORIG_REF_NAME==bd_525a_eth_mac_0}]

# IP: c:/Users/Berk/Desktop/FPGA/UMRAM/Ethernet/Ethernet.srcs/sources_1/bd/design_1/ip/design_1_axi_ethernet_0_1/bd_0/ip/ip_2/bd_525a_pcs_pma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_525a_pcs_pma_0 || ORIG_REF_NAME==bd_525a_pcs_pma_0}]

# IP: c:/Users/Berk/Desktop/FPGA/UMRAM/Ethernet/Ethernet.srcs/sources_1/bd/design_1/ip/design_1_axi_ethernet_0_1/bd_0/ip/ip_3/bd_525a_xlconstant_phyadd_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_525a_xlconstant_phyadd_0 || ORIG_REF_NAME==bd_525a_xlconstant_phyadd_0}]

# XDC: c:/Users/Berk/Desktop/FPGA/UMRAM/Ethernet/Ethernet.srcs/sources_1/bd/design_1/ip/design_1_axi_ethernet_0_1/bd_0/bd_525a_ooc.xdc

# XDC: c:/Users/Berk/Desktop/FPGA/UMRAM/Ethernet/Ethernet.srcs/sources_1/bd/design_1/ip/design_1_axi_ethernet_0_1/synth/design_1_axi_ethernet_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_ethernet_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/Berk/Desktop/FPGA/UMRAM/Ethernet/Ethernet.srcs/sources_1/bd/design_1/ip/design_1_axi_ethernet_0_1/design_1_axi_ethernet_0_1.xci
# IP: The module: 'design_1_axi_ethernet_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/Berk/Desktop/FPGA/UMRAM/Ethernet/Ethernet.srcs/sources_1/bd/design_1/ip/design_1_axi_ethernet_0_1/bd_0/bd_525a.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_525a || ORIG_REF_NAME==bd_525a}]

# IP: c:/Users/Berk/Desktop/FPGA/UMRAM/Ethernet/Ethernet.srcs/sources_1/bd/design_1/ip/design_1_axi_ethernet_0_1/bd_0/ip/ip_0/bd_525a_eth_buf_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_525a_eth_buf_0 || ORIG_REF_NAME==bd_525a_eth_buf_0}]

# IP: c:/Users/Berk/Desktop/FPGA/UMRAM/Ethernet/Ethernet.srcs/sources_1/bd/design_1/ip/design_1_axi_ethernet_0_1/bd_0/ip/ip_1/bd_525a_eth_mac_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_525a_eth_mac_0 || ORIG_REF_NAME==bd_525a_eth_mac_0}]

# IP: c:/Users/Berk/Desktop/FPGA/UMRAM/Ethernet/Ethernet.srcs/sources_1/bd/design_1/ip/design_1_axi_ethernet_0_1/bd_0/ip/ip_2/bd_525a_pcs_pma_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_525a_pcs_pma_0 || ORIG_REF_NAME==bd_525a_pcs_pma_0}]

# IP: c:/Users/Berk/Desktop/FPGA/UMRAM/Ethernet/Ethernet.srcs/sources_1/bd/design_1/ip/design_1_axi_ethernet_0_1/bd_0/ip/ip_3/bd_525a_xlconstant_phyadd_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_525a_xlconstant_phyadd_0 || ORIG_REF_NAME==bd_525a_xlconstant_phyadd_0}]

# XDC: c:/Users/Berk/Desktop/FPGA/UMRAM/Ethernet/Ethernet.srcs/sources_1/bd/design_1/ip/design_1_axi_ethernet_0_1/bd_0/bd_525a_ooc.xdc

# XDC: c:/Users/Berk/Desktop/FPGA/UMRAM/Ethernet/Ethernet.srcs/sources_1/bd/design_1/ip/design_1_axi_ethernet_0_1/synth/design_1_axi_ethernet_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_ethernet_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
