# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/dizaynnn/dizaynnn.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dizaynnn || ORIG_REF_NAME==dizaynnn}]

# IP: bd/dizaynnn/ip/dizaynnn_Robust_Module_0_0/dizaynnn_Robust_Module_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dizaynnn_Robust_Module_0_0 || ORIG_REF_NAME==dizaynnn_Robust_Module_0_0}]

# IP: bd/dizaynnn/ip/dizaynnn_clk_wiz_0_0/dizaynnn_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dizaynnn_clk_wiz_0_0 || ORIG_REF_NAME==dizaynnn_clk_wiz_0_0}]

# IP: bd/dizaynnn/ip/dizaynnn_blk_mem_gen_0_0/dizaynnn_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dizaynnn_blk_mem_gen_0_0 || ORIG_REF_NAME==dizaynnn_blk_mem_gen_0_0}]

# XDC: bd/dizaynnn/dizaynnn_ooc.xdc
